### ISSUE TITLE
Bot can't download attachments larger than 20 MB.

### ISSUE THREAD

**Issue by DeNcHiK3713** [Amaimersion/yandex-disk-telegram-bot#3]
# Bug Report

Bot can't download attachments larger than 20 MB.

## Expected Behavior

Upload files up to 1.5 GB in size.

## Actual Behavior

If the attachment larger than 20 MB, the bot replies:
```At the moment i can't process this because of my internal error. Try later please.```

## Additional Information

[The same issue.](https://github.com/yagop/node-telegram-bot-api/issues/736)
[Possible way to bypass limitation](https://habr.com/ru/post/348234/)

**Comment by bahramzade** [comment]
++

**Comment by Amaimersion** [comment]
Hello!

Yes, there is some limitations and there is no logic in code to handle this.

Sorry for late response. At the moment i don't have a time to work on it. It will be implemented, but later.

**Comment by Amaimersion** [comment]
Files up to 1.5 GB can be uploaded via Telegram Client for users (using only API, of course). At the moment i will add warning about 20 MB limit, but in the future i will try to implement uploading of files up to 1.5 GB.

**Comment by Amaimersion** [comment]
https://github.com/Amaimersion/yandex-disk-telegram-bot/commit/e2d1af54377b4aa39450a2af8e204ae405efe06b
